[antlers]
submodule = "extensions/antlers"
version = "0.1.5.1"

id = "statamic-antlers"
name = "Statamic Antlers"
version = "0.1.5.1"
schema_version = 1
authors = ["Joachim Rütter <me@mynetx.net>", "Devin Green <design@devingreen.me>"]
description = "Syntax highlighting and IntelliSense for Statamic Antlers in Zed"
repository = "https://github.com/mynetx/zed-statamic-antlers"

[grammars.antlers]
repository = "https://github.com/artistro08/tree-sitter-antlers"
commit = "6fa41760fd1f3bb4488e841666c8dfab3c290a4c"

[language_servers.vscode-antlers-language-server]
name = "Statamic Antlers Language Server"
language = "Statamic Antlers"
